export const GUESTS: Guests = [
  {
    name: '主桌',
    category: '主桌',
    tableId: 1,
    list: [
      {
        key: 'táng péi lún',
        confirm: true,
        value: '唐培倫',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhèng wéi xīn',
        confirm: true,
        value: '鄭惟心',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'táng yáng zhèng',
        confirm: true,
        value: '唐鍚正',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén shùn huà',
        confirm: true,
        value: '陳舜華',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhèng wén bīn',
        confirm: true,
        value: '鄭文彬',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'guō yǎn lì',
        confirm: true,
        value: '郭衍利',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'xú yù fāng',
        confirm: true,
        value: '徐郁芳',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhèng wéi rén',
        confirm: true,
        value: '鄭惟仁',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'fù yōng ní',
        confirm: true,
        value: '傅雍霓',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhèng xǐ xuān',
        confirm: true,
        value: '鄭禧宣',
        needBabySeat: true,
        companions: 0,
      },
      {
        key: 'zhèng hàn ēn',
        confirm: true,
        value: '鄭翰恩',
        needBabySeat: true,
        companions: 0,
      },
    ],
  },
  {
    name: '91APP',
    category: '91APP',
    tableId: 2,
    list: [
      {
        key: 'péng shī xiào',
        confirm: true,
        value: '彭師孝',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhāng yǔ 1',
        confirm: true,
        value: '張瑀',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'zhāng yǔ 2',
        confirm: true,
        value: '張瑀',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'lǐ kuān wěi 1',
        confirm: true,
        value: '李寬瑋',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'lǐ kuān wěi 2',
        confirm: true,
        value: '李寬瑋',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'qín guó xióng',
        confirm: true,
        value: '秦國雄',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén pǐn róng 1',
        confirm: true,
        value: '陳品融',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'chén pǐn róng 2',
        confirm: true,
        value: '陳品融',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'chén pǐn róng 3',
        confirm: true,
        value: '陳品融',
        needBabySeat: true,
        companions: 3,
      },
    ],
  },
  {
    name: 'TheOne',
    category: 'TheOne',
    tableId: 3,
    list: [
      {
        key: 'chǔ zhì xuān',
        confirm: true,
        value: '褚治軒',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'xùn jié rú',
        confirm: true,
        value: '孫婕茹',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'xū jiā rú',
        confirm: true,
        value: '許嘉儒',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén xuān yào',
        confirm: true,
        value: '陳宣耀',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'liào yì tíng',
        confirm: true,
        value: '廖翊廷',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'wáng mèng fàn',
        confirm: true,
        value: '王孟梵',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lín shēng hàn',
        confirm: true,
        value: '林昇翰',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'liáng róng',
        confirm: true,
        value: '梁容',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lǐ yī róu',
        confirm: false,
        value: '李依柔',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '安提阿',
    category: '安提阿',
    tableId: 4,
    list: [
      {
        key: 'lín jiǔ měi',
        confirm: true,
        value: '林久美',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén qí yuè',
        confirm: true,
        value: '陳奇樂',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén bǎi hàn',
        confirm: true,
        value: '陳柏翰',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'huáng yàn jūn',
        confirm: true,
        value: '黃彥鈞',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'huáng jié',
        confirm: true,
        value: '黃婕',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'huáng jié',
        confirm: true,
        value: '黃婕',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lǐ xīn yí',
        confirm: true,
        value: '李芯儀',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'wú míng zhé',
        confirm: true,
        value: '吳鳴哲',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '秀朗國小',
    category: '秀朗國小',
    tableId: 5,
    list: [
      {
        key: 'lín qìng zhēn',
        confirm: true,
        value: '林慶貞',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'cài xiāng líng',
        confirm: true,
        value: '蔡香玲',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'dù jì róng',
        confirm: true,
        value: '杜季容',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'cài yàn yì',
        confirm: true,
        value: '蔡彥誼',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'luó xiù huì',
        confirm: true,
        value: '羅秀惠',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lín fāng yǎng',
        confirm: true,
        value: '林芳仰',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lǐ jiàn xīng',
        confirm: true,
        value: '李建興',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'liào yíng zhí',
        confirm: true,
        value: '廖瑩職',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '青年牧區 1',
    category: '青年牧區',
    tableId: 6,
    list: [
      {
        key: 'lín yù hóng',
        confirm: true,
        value: '林昱宏',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'fàn shì yǎng',
        confirm: true,
        value: '范仕仰',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'wáng xī héng',
        confirm: true,
        value: '王曦珩',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'liú zhǔ wēi',
        confirm: true,
        value: '劉主威',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'fāng xīn 1',
        confirm: true,
        value: '方心',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'fāng xīn 2',
        confirm: true,
        value: '方心',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'fāng xīn 3',
        confirm: true,
        value: '方心',
        needBabySeat: true,
        companions: 3,
      },
      {
        key: 'yáng yí xīn',
        confirm: true,
        value: '楊怡馨',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '青年牧區 2',
    category: '青年牧區',
    tableId: 7,
    list: [
      {
        key: 'zhāng yǎ líng',
        confirm: true,
        value: '張雅綾',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'cài xī píng',
        confirm: true,
        value: '蔡熙平',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'gāo jié',
        confirm: true,
        value: '高倢',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'wáng jìng yuān',
        confirm: true,
        value: '王鏡淵',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén zhēn',
        confirm: true,
        value: '陳箴',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'cài péi huà',
        confirm: true,
        value: '蔡培華',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lín sù zhēn',
        confirm: true,
        value: '林素真',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'dǒng jiā yīn',
        confirm: true,
        value: '董佳音',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '女方大學同學 1',
    category: '女方大學同學',
    tableId: 8,
    list: [
      {
        key: 'huáng sī jiā 1',
        confirm: true,
        value: '黃思嘉',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'huáng sī jiā 2',
        confirm: true,
        value: '黃思嘉',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'lǐ yún yíng 1',
        confirm: true,
        value: '李芸螢',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'lǐ yún yíng 2',
        confirm: true,
        value: '李芸螢',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'liú pǐn xuān',
        confirm: true,
        value: '劉品萱',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'liú zhī píng 1',
        confirm: true,
        value: '劉之屏',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'liú zhī píng 2',
        confirm: true,
        value: '劉之屏',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'jiāng yí tíng',
        confirm: true,
        value: '江宜庭',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '女方大學同學 2',
    category: '女方大學同學',
    tableId: 9,
    list: [
      {
        key: 'méi jiā xīng 1',
        confirm: true,
        value: '梅嘉興',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'méi jiā xīng 2',
        confirm: true,
        value: '梅嘉興',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'lín wēi chéng',
        confirm: true,
        value: '林威成',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'hán zhōu',
        confirm: true,
        value: '韓周',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhū zǐ jūn',
        confirm: true,
        value: '朱子君',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhāng yún hào',
        confirm: true,
        value: '張雲皓',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén pǐn yú',
        confirm: true,
        value: '陳品瑜',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '男方媽媽親友 1',
    category: '男方媽媽親友',
    tableId: 10,
    list: [
      {
        key: 'zhāng yào rén 1',
        confirm: true,
        value: '張耀仁',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'zhāng yào rén 2',
        confirm: true,
        value: '張耀仁',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'A s h l e y',
        confirm: true,
        value: 'Ashley',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'A n n',
        confirm: true,
        value: 'Ann',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'S a n d y',
        confirm: true,
        value: 'Sandy',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'V i v i a n',
        confirm: true,
        value: 'Vivian',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'jiāng měi zhēn 1',
        confirm: true,
        value: '江美貞',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'jiāng měi zhēn 2',
        confirm: true,
        value: '江美貞',
        needBabySeat: false,
        companions: 2,
      },
    ],
  },
  {
    name: '男方媽媽親友 2',
    category: '男方媽媽親友',
    tableId: 11,
    list: [
      {
        key: 'chén shùn píng 1',
        confirm: true,
        value: '陳舜蘋',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'chén shùn píng 2',
        confirm: true,
        value: '陳舜蘋',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'chén shùn píng 3',
        confirm: true,
        value: '陳舜蘋',
        needBabySeat: false,
        companions: 3,
      },
      {
        key: 'chén shùn píng 4',
        confirm: true,
        value: '陳舜蘋',
        needBabySeat: false,
        companions: 4,
      },
      {
        key: 'gāo měi zhū',
        confirm: true,
        value: '高美珠',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'gāo měi yún',
        confirm: true,
        value: '高美雲',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'gāo shū yuàn',
        confirm: true,
        value: '高淑媛',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhāng miào líng',
        confirm: true,
        value: '張妙綾',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '男方爸爸親友 1',
    category: '男方爸爸親友',
    tableId: 12,
    list: [
      {
        key: 'wèi bó zhòng 1',
        confirm: true,
        value: '魏伯仲',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'wèi bó zhòng 2',
        confirm: true,
        value: '魏伯仲',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'wèi bó zhòng 3',
        confirm: true,
        value: '魏伯仲',
        needBabySeat: true,
        companions: 3,
      },
      {
        key: 'wèi cí huì 1',
        confirm: true,
        value: '魏慈慧',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'wèi cí huì 2',
        confirm: true,
        value: '魏慈慧',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'wèi cí huì 3',
        confirm: true,
        value: '魏慈慧',
        needBabySeat: false,
        companions: 3,
      },
      {
        key: 'táng wěi lún 1',
        confirm: true,
        value: '唐韡倫',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'táng wěi lún 2',
        confirm: true,
        value: '唐韡倫',
        needBabySeat: false,
        companions: 2,
      },
    ],
  },
  {
    name: '男方爸爸親友 2',
    category: '男方爸爸親友',
    tableId: 13,
    list: [
      {
        key: 'táng yáng zhì 1',
        confirm: true,
        value: '唐鍚志',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'táng yáng zhì 2',
        confirm: true,
        value: '唐鍚志',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'táng yáng zhì 3',
        confirm: true,
        value: '唐鍚志',
        needBabySeat: false,
        companions: 3,
      },
      {
        key: 'huáng shèng zhù 1',
        confirm: true,
        value: '黃勝助',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'huáng shèng zhù 2',
        confirm: true,
        value: '黃勝助',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'chén yí zhēn 1',
        confirm: true,
        value: '陳怡珍',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'chén yí zhēn 2',
        confirm: true,
        value: '陳怡珍',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'chén yí zhēn 3',
        confirm: true,
        value: '陳怡珍',
        needBabySeat: false,
        companions: 3,
      },
    ],
  },
  {
    name: '男方爸爸親友 3',
    category: '男方爸爸親友',
    tableId: 14,
    list: [
      {
        key: 'chén zōng tíng 1',
        confirm: true,
        value: '陳宗庭',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'chén zōng tíng 2',
        confirm: true,
        value: '陳宗庭',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'xú zhì fēng 1',
        confirm: true,
        value: '徐志豐',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'xú zhì fēng 2',
        confirm: true,
        value: '徐志豐',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'lǐ guó bīn',
        confirm: true,
        value: '李國賓',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén yì shēng 1',
        confirm: true,
        value: '陳逸升',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'chén yì shēng 2',
        confirm: true,
        value: '陳逸升',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'chén yì shēng 3',
        confirm: true,
        value: '陳逸升',
        needBabySeat: false,
        companions: 3,
      },
      {
        key: 'liáng xuān xián',
        confirm: true,
        value: '梁瑄賢',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'zhōng míng',
        confirm: false,
        value: '鐘明',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: '女方親友',
    category: '女方親友',
    tableId: 15,
    list: [
      {
        key: 'zhèng hán wèi 1',
        confirm: true,
        value: '鄭涵蔚',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'zhèng hán wèi 2',
        confirm: true,
        value: '鄭涵蔚',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'zhèng mù xī 1',
        confirm: true,
        value: '鄭慕曦',
        needBabySeat: false,
        companions: 1,
      },
      {
        key: 'zhèng mù xī 2',
        confirm: true,
        value: '鄭慕曦',
        needBabySeat: false,
        companions: 2,
      },
      {
        key: 'zhèng wén fēng',
        confirm: true,
        value: '鄭文峰',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'qiū wǎn qí',
        confirm: true,
        value: '邱婉琪',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
  {
    name: 'Amazingtalker',
    category: 'Amazingtalker',
    tableId: 16,
    list: [
      {
        key: 'yáng yǒng rèn',
        confirm: true,
        value: '楊永任',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén qín huà',
        confirm: true,
        value: '陳芹嬅',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'dǒng zhòng xuān',
        confirm: true,
        value: '董仲軒',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'qiū zhì háo',
        confirm: true,
        value: '邱志豪',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'lǚ háo shèng',
        confirm: true,
        value: '呂豪晟',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'xiè shū tíng',
        confirm: true,
        value: '謝書庭',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén bǎi ān',
        confirm: true,
        value: '陳柏安',
        needBabySeat: false,
        companions: 0,
      },
      {
        key: 'chén yì ān',
        confirm: true,
        value: '陳奕安',
        needBabySeat: false,
        companions: 0,
      },
    ],
  },
]

export const TABLE_COUNT = GUESTS.length

export const TOTAL = GUESTS.reduce((collection, { list }) => collection + list.length, 0)

export const UN_CONFIRM_LIST = GUESTS.reduce((collection: TableListItem[], { list }) => {
  const unConfirmListByTable = list.filter(item => !item.confirm)
  return collection.concat(unConfirmListByTable)
}, [])

export const BABY_LIST = GUESTS.reduce((collection: TableListItem[], { list }) => {
  const babyListListByTable = list.filter(item => item.needBabySeat)
  return collection.concat(babyListListByTable)
}, [])
